baseURL = "https://www.webosose.org"
title = "webOS Open Source Edition"

enableRobotsTXT = true

contentDir = "content/en"

disableKinds = ["taxonomy", "taxonomyTerm"]

# Syntax Highlighting
pygmentsUseClassic = false
pygmentsCodeFences = true
pygmentsUseClasses = false
# See https://xyproto.github.io/splash/docs/longer/all.html
pygmentsStyle = "friendly"

[markup]
  [markup.goldmark]
    [markup.goldmark.parser]
      autoHeadingIDType = "blackfriday"
    [markup.goldmark.renderer]
      unsafe = true

[outputs]
home = [ "HTML" ]
page = [ "HTML" ]
section = [ "HTML" ]

[permalinks]
blog = "/:section/:year/:month/:day/:slug/"
samples = "/:section/:year/:month/:day/:slug/"

# See https://gohugo.io/content-management/menus/
[menu]
  [[menu.main]]
    identifier = "about"
    name = "about"
    url = "/about/"
    weight = -140

  [[menu.main]]
    identifier = "docs"
    name = "docs"
    url = "/docs/"
    weight = -130

  [[menu.main]]
    identifier = "blog"
    name = "blog"
    url = "/blog/"
    weight = -120

  [[menu.main]]
    identifier = "samples"
    name = "samples"
    url = "/samples/"
    weight = -110

  [[menu.main]]
    identifier = "community"
    name = "community"
    url = "/community/"
    weight = -100

[params]
time_format = "January 02, 2006"

# Security configuration from https://github.com/gohugoio/hugo/releases/tag/v0.91.0
[security]
  enableInlineShortcodes = false
  [security.exec]
    allow = ['^dart-sass-embedded$', '^go$', '^npx$', '^postcss$']
    osEnv = ['(?i)^(PATH|PATHEXT|APPDATA|TMP|TEMP|TERM)$']

  [security.funcs]
    getenv = ['^HUGO_', '^SEARCH_'] # See https://answers.netlify.com/t/failed-to-deploy-website-command-failed-with-exit-code-255/83002/2

  [security.http]
    methods = ['(?i)GET|POST']
    urls = ['.*']